services:
  PayPay\OpenPaymentAPI\Client:
    arguments:
      - API_KEY: '%env(PAYPAY_API_KEY)%'
        API_SECRET: '%env(PAYPAY_API_SECRET)%'
        MERCHANT_ID: '%env(PAYPAY_MERCHANT_ID)%'
      - '%env(PAYPAY_TEST)%'
